export interface EmojiData {
  emoji: string;
  name: string;
  category: string;
}

export const EMOJI_LIST: EmojiData[] = [
  // Smileys & Emotion
  { emoji: '😀', name: 'grinning', category: 'Smileys' },
  { emoji: '😃', name: 'smiley', category: 'Smileys' },
  { emoji: '😄', name: 'smile', category: 'Smileys' },
  { emoji: '😁', name: 'grin', category: 'Smileys' },
  { emoji: '😆', name: 'laughing', category: 'Smileys' },
  { emoji: '😅', name: 'sweat smile', category: 'Smileys' },
  { emoji: '🤣', name: 'rofl', category: 'Smileys' },
  { emoji: '😂', name: 'joy', category: 'Smileys' },
  { emoji: '🙂', name: 'slight smile', category: 'Smileys' },
  { emoji: '🙃', name: 'upside down', category: 'Smileys' },
  { emoji: '😉', name: 'wink', category: 'Smileys' },
  { emoji: '😊', name: 'blush', category: 'Smileys' },
  { emoji: '😇', name: 'innocent', category: 'Smileys' },
  { emoji: '🥰', name: 'smiling face with hearts', category: 'Smileys' },
  { emoji: '😍', name: 'heart eyes', category: 'Smileys' },
  { emoji: '🤩', name: 'star struck', category: 'Smileys' },
  { emoji: '😘', name: 'kissing heart', category: 'Smileys' },
  { emoji: '😗', name: 'kissing', category: 'Smileys' },
  { emoji: '😚', name: 'kissing closed eyes', category: 'Smileys' },
  { emoji: '😋', name: 'yum', category: 'Smileys' },
  { emoji: '😛', name: 'stuck out tongue', category: 'Smileys' },
  { emoji: '😜', name: 'stuck out tongue winking eye', category: 'Smileys' },
  { emoji: '🤪', name: 'zany face', category: 'Smileys' },
  { emoji: '🤨', name: 'raised eyebrow', category: 'Smileys' },
  { emoji: '🧐', name: 'monocle', category: 'Smileys' },
  { emoji: '🤓', name: 'nerd', category: 'Smileys' },
  { emoji: '😎', name: 'sunglasses', category: 'Smileys' },
  { emoji: '🥳', name: 'partying face', category: 'Smileys' },
  { emoji: '😏', name: 'smirk', category: 'Smileys' },
  { emoji: '😒', name: 'unamused', category: 'Smileys' },
  { emoji: '😞', name: 'disappointed', category: 'Smileys' },
  { emoji: '😔', name: 'pensive', category: 'Smileys' },
  { emoji: '😟', name: 'worried', category: 'Smileys' },
  { emoji: '😕', name: 'confused', category: 'Smileys' },
  { emoji: '😫', name: 'tired', category: 'Smileys' },
  { emoji: '🥵', name: 'hot face', category: 'Smileys' },
  { emoji: '🥶', name: 'cold face', category: 'Smileys' },
  { emoji: '😳', name: 'flushed', category: 'Smileys' },
  { emoji: '😱', name: 'scream', category: 'Smileys' },
  { emoji: '🤢', name: 'nauseated', category: 'Smileys' },
  { emoji: '🤮', name: 'vomiting', category: 'Smileys' },
  { emoji: '🤬', name: 'cursing', category: 'Smileys' },
  { emoji: '🤫', name: 'shushing', category: 'Smileys' },
  { emoji: '🤔', name: 'thinking', category: 'Smileys' },
  { emoji: '🤗', name: 'hugs', category: 'Smileys' },
  { emoji: '🥱', name: 'yawn', category: 'Smileys' },
  { emoji: '😴', name: 'sleeping', category: 'Smileys' },
  { emoji: '🤤', name: 'drooling', category: 'Smileys' },
  { emoji: '😵', name: 'dizzy', category: 'Smileys' },
  { emoji: '🤐', name: 'zipper mouth', category: 'Smileys' },
  { emoji: '🥴', name: 'woozy', category: 'Smileys' },
  { emoji: '🤒', name: 'fever', category: 'Smileys' },
  { emoji: '🤕', name: 'bandage', category: 'Smileys' },
  { emoji: '🤡', name: 'clown', category: 'Smileys' },
  { emoji: '👻', name: 'ghost', category: 'Smileys' },
  { emoji: '👽', name: 'alien', category: 'Smileys' },
  { emoji: '👾', name: 'robot', category: 'Smileys' },
  { emoji: '💩', name: 'poop', category: 'Smileys' },

  // Hearts & Symbols
  { emoji: '❤️', name: 'heart', category: 'Symbols' },
  { emoji: '🧡', name: 'orange heart', category: 'Symbols' },
  { emoji: '💛', name: 'yellow heart', category: 'Symbols' },
  { emoji: '💚', name: 'green heart', category: 'Symbols' },
  { emoji: '💙', name: 'blue heart', category: 'Symbols' },
  { emoji: '💜', name: 'purple heart', category: 'Symbols' },
  { emoji: '🖤', name: 'black heart', category: 'Symbols' },
  { emoji: '🤍', name: 'white heart', category: 'Symbols' },
  { emoji: '🤎', name: 'brown heart', category: 'Symbols' },
  { emoji: '💔', name: 'broken heart', category: 'Symbols' },
  { emoji: '❣️', name: 'heart exclamation', category: 'Symbols' },
  { emoji: '💕', name: 'two hearts', category: 'Symbols' },
  { emoji: '💞', name: 'revolving hearts', category: 'Symbols' },
  { emoji: '✨', name: 'sparkles', category: 'Symbols' },
  { emoji: '🔥', name: 'fire', category: 'Symbols' },
  { emoji: '⭐', name: 'star', category: 'Symbols' },
  { emoji: '🌟', name: 'glowing star', category: 'Symbols' },
  { emoji: '✅', name: 'check', category: 'Symbols' },
  { emoji: '❌', name: 'cross', category: 'Symbols' },
  { emoji: '💯', name: 'hundred', category: 'Symbols' },
  { emoji: '💢', name: 'anger', category: 'Symbols' },
  { emoji: '💥', name: 'collision', category: 'Symbols' },
  { emoji: '💫', name: 'dizzy symbol', category: 'Symbols' },
  { emoji: '💦', name: 'sweat drops', category: 'Symbols' },
  { emoji: '💨', name: 'dash', category: 'Symbols' },
  
  // Hand Gestures
  { emoji: '👍', name: 'thumbs up', category: 'Hands' },
  { emoji: '👎', name: 'thumbs down', category: 'Hands' },
  { emoji: '👌', name: 'ok', category: 'Hands' },
  { emoji: '✌️', name: 'victory', category: 'Hands' },
  { emoji: '🤞', name: 'fingers crossed', category: 'Hands' },
  { emoji: '🤟', name: 'rock on', category: 'Hands' },
  { emoji: '🤘', name: 'horns', category: 'Hands' },
  { emoji: '🤙', name: 'call me', category: 'Hands' },
  { emoji: '👈', name: 'point left', category: 'Hands' },
  { emoji: '👉', name: 'point right', category: 'Hands' },
  { emoji: '👆', name: 'point up', category: 'Hands' },
  { emoji: '👇', name: 'point down', category: 'Hands' },
  { emoji: '🖐️', name: 'hand splayed', category: 'Hands' },
  { emoji: '✋', name: 'raised hand', category: 'Hands' },
  { emoji: '🖖', name: 'vulcan salute', category: 'Hands' },
  { emoji: '👋', name: 'wave', category: 'Hands' },
  { emoji: '👏', name: 'clap', category: 'Hands' },
  { emoji: '🙌', name: 'hands up', category: 'Hands' },
  { emoji: '👐', name: 'open hands', category: 'Hands' },
  { emoji: '🤲', name: 'palms up', category: 'Hands' },
  { emoji: '🤝', name: 'handshake', category: 'Hands' },
  { emoji: '🙏', name: 'pray', category: 'Hands' },
  { emoji: '💪', name: 'flex', category: 'Hands' },
  { emoji: '✍️', name: 'writing', category: 'Hands' },
  { emoji: '🤳', name: 'selfie', category: 'Hands' },

  // Animals & Nature
  { emoji: '🐶', name: 'dog', category: 'Animals' },
  { emoji: '🐱', name: 'cat', category: 'Animals' },
  { emoji: '🐭', name: 'mouse', category: 'Animals' },
  { emoji: '🐹', name: 'hamster', category: 'Animals' },
  { emoji: '🐰', name: 'rabbit', category: 'Animals' },
  { emoji: '🦊', name: 'fox', category: 'Animals' },
  { emoji: '🐻', name: 'bear', category: 'Animals' },
  { emoji: '🐼', name: 'panda', category: 'Animals' },
  { emoji: '🐨', name: 'koala', category: 'Animals' },
  { emoji: '🐯', name: 'tiger', category: 'Animals' },
  { emoji: '🦁', name: 'lion', category: 'Animals' },
  { emoji: '🐮', name: 'cow', category: 'Animals' },
  { emoji: '🐷', name: 'pig', category: 'Animals' },
  { emoji: '🐸', name: 'frog', category: 'Animals' },
  { emoji: '🐵', name: 'monkey', category: 'Animals' },
  { emoji: '🐔', name: 'chicken', category: 'Animals' },
  { emoji: '🐧', name: 'penguin', category: 'Animals' },
  { emoji: '🐦', name: 'bird', category: 'Animals' },
  { emoji: '🐤', name: 'chick', category: 'Animals' },
  { emoji: '🦆', name: 'duck', category: 'Animals' },
  { emoji: '🦅', name: 'eagle', category: 'Animals' },
  { emoji: '🦉', name: 'owl', category: 'Animals' },
  { emoji: '🦇', name: 'bat', category: 'Animals' },
  { emoji: '🦄', name: 'unicorn', category: 'Animals' },
  { emoji: '🐝', name: 'bee', category: 'Animals' },
  { emoji: '🦋', name: 'butterfly', category: 'Animals' },
  { emoji: '🐌', name: 'snail', category: 'Animals' },
  { emoji: '🐞', name: 'ladybeetle', category: 'Animals' },
  { emoji: '🐢', name: 'turtle', category: 'Animals' },
  { emoji: '🐍', name: 'snake', category: 'Animals' },
  { emoji: '🐙', name: 'octopus', category: 'Animals' },
  { emoji: '🐬', name: 'dolphin', category: 'Animals' },
  { emoji: '🐳', name: 'whale', category: 'Animals' },
  { emoji: '🐟', name: 'fish', category: 'Animals' },
  { emoji: '🦓', name: 'zebra', category: 'Animals' },
  { emoji: '🦒', name: 'giraffe', category: 'Animals' },
  { emoji: '🐘', name: 'elephant', category: 'Animals' },
  { emoji: '🦏', name: 'rhino', category: 'Animals' },
  { emoji: '🐪', name: 'camel', category: 'Animals' },
  { emoji: '🐒', name: 'monkey', category: 'Animals' },
  
  // Food & Drink
  { emoji: '🍎', name: 'apple', category: 'Food' },
  { emoji: '🍐', name: 'pear', category: 'Food' },
  { emoji: '🍊', name: 'tangerine', category: 'Food' },
  { emoji: '🍋', name: 'lemon', category: 'Food' },
  { emoji: '🍌', name: 'banana', category: 'Food' },
  { emoji: '🍉', name: 'watermelon', category: 'Food' },
  { emoji: '🍇', name: 'grapes', category: 'Food' },
  { emoji: '🍓', name: 'strawberry', category: 'Food' },
  { emoji: '🍒', name: 'cherries', category: 'Food' },
  { emoji: '🍑', name: 'peach', category: 'Food' },
  { emoji: '🥭', name: 'mango', category: 'Food' },
  { emoji: '🍍', name: 'pineapple', category: 'Food' },
  { emoji: '🥥', name: 'coconut', category: 'Food' },
  { emoji: '🥝', name: 'kiwi', category: 'Food' },
  { emoji: '🍅', name: 'tomato', category: 'Food' },
  { emoji: '🥑', name: 'avocado', category: 'Food' },
  { emoji: '🍆', name: 'eggplant', category: 'Food' },
  { emoji: '🥔', name: 'potato', category: 'Food' },
  { emoji: '🥕', name: 'carrot', category: 'Food' },
  { emoji: '🌽', name: 'corn', category: 'Food' },
  { emoji: '🌶️', name: 'hot pepper', category: 'Food' },
  { emoji: '🥦', name: 'broccoli', category: 'Food' },
  { emoji: '🍄', name: 'mushroom', category: 'Food' },
  { emoji: '🥜', name: 'peanuts', category: 'Food' },
  { emoji: '🍞', name: 'bread', category: 'Food' },
  { emoji: '🥐', name: 'croissant', category: 'Food' },
  { emoji: '🥯', name: 'bagel', category: 'Food' },
  { emoji: '🥞', name: 'pancakes', category: 'Food' },
  { emoji: '🧀', name: 'cheese', category: 'Food' },
  { emoji: '🍖', name: 'meat', category: 'Food' },
  { emoji: '🍗', name: 'poultry leg', category: 'Food' },
  { emoji: '🥓', name: 'bacon', category: 'Food' },
  { emoji: '🍔', name: 'hamburger', category: 'Food' },
  { emoji: '🍟', name: 'fries', category: 'Food' },
  { emoji: '🍕', name: 'pizza', category: 'Food' },
  { emoji: '🌭', name: 'hot dog', category: 'Food' },
  { emoji: '🥪', name: 'sandwich', category: 'Food' },
  { emoji: '🌮', name: 'taco', category: 'Food' },
  { emoji: '🌯', name: 'burrito', category: 'Food' },
  { emoji: '🍳', name: 'egg', category: 'Food' },
  { emoji: '🍲', name: 'stew', category: 'Food' },
  { emoji: '🥣', name: 'bowl', category: 'Food' },
  { emoji: '🥗', name: 'salad', category: 'Food' },
  { emoji: '🍿', name: 'popcorn', category: 'Food' },
  { emoji: '🍱', name: 'bento', category: 'Food' },
  { emoji: '🍣', name: 'sushi', category: 'Food' },
  { emoji: '🍤', name: 'shrimp', category: 'Food' },
  { emoji: '🍦', name: 'ice cream', category: 'Food' },
  { emoji: '🍧', name: 'shaved ice', category: 'Food' },
  { emoji: '🍨', name: 'ice cream', category: 'Food' },
  { emoji: '🍩', name: 'donut', category: 'Food' },
  { emoji: '🍪', name: 'cookie', category: 'Food' },
  { emoji: '🎂', name: 'cake', category: 'Food' },
  { emoji: '🍰', name: 'shortcake', category: 'Food' },
  { emoji: '🧁', name: 'cupcake', category: 'Food' },
  { emoji: '🥧', name: 'pie', category: 'Food' },
  { emoji: '🍫', name: 'chocolate', category: 'Food' },
  { emoji: '🍬', name: 'candy', category: 'Food' },
  { emoji: '🍭', name: 'lollipop', category: 'Food' },
  { emoji: '🍮', name: 'custard', category: 'Food' },
  { emoji: '🍯', name: 'honey', category: 'Food' },
  { emoji: '🍼', name: 'baby bottle', category: 'Food' },
  { emoji: '🥛', name: 'milk', category: 'Food' },
  { emoji: '☕', name: 'coffee', category: 'Food' },
  { emoji: '🍵', name: 'tea', category: 'Food' },
  { emoji: '🍶', name: 'sake', category: 'Food' },
  { emoji: '🍾', name: 'champagne', category: 'Food' },
  { emoji: '🍷', name: 'wine', category: 'Food' },
  { emoji: '🍸', name: 'cocktail', category: 'Food' },
  { emoji: '🍹', name: 'tropical drink', category: 'Food' },
  { emoji: '🍺', name: 'beer', category: 'Food' },
  { emoji: '🍻', name: 'beers', category: 'Food' },
  { emoji: '🥃', name: 'tumbler glass', category: 'Food' },
  { emoji: '🥤', name: 'soda', category: 'Food' },

  // Travel & Places
  { emoji: '🚗', name: 'car', category: 'Travel' },
  { emoji: '🚕', name: 'taxi', category: 'Travel' },
  { emoji: '🚙', name: 'bus', category: 'Travel' },
  { emoji: '🚌', name: 'trolleybus', category: 'Travel' },
  { emoji: '🏎️', name: 'racing car', category: 'Travel' },
  { emoji: '🚓', name: 'police car', category: 'Travel' },
  { emoji: '🚑', name: 'ambulance', category: 'Travel' },
  { emoji: '🚒', name: 'fire engine', category: 'Travel' },
  { emoji: '🚐', name: 'minibus', category: 'Travel' },
  { emoji: '🚚', name: 'truck', category: 'Travel' },
  { emoji: '🚛', name: 'articulated lorry', category: 'Travel' },
  { emoji: '🚜', name: 'tractor', category: 'Travel' },
  { emoji: '🚲', name: 'bicycle', category: 'Travel' },
  { emoji: '🛵', name: 'scooter', category: 'Travel' },
  { emoji: '🏍️', name: 'motorcycle', category: 'Travel' },
  { emoji: '🚄', name: 'bullet train', category: 'Travel' },
  { emoji: '🚆', name: 'train', category: 'Travel' },
  { emoji: '✈️', name: 'airplane', category: 'Travel' },
  { emoji: '🚀', name: 'rocket', category: 'Travel' },
  { emoji: '🛸', name: 'ufo', category: 'Travel' },
  { emoji: '🚁', name: 'helicopter', category: 'Travel' },
  { emoji: '🚢', name: 'ship', category: 'Travel' },
  { emoji: '⛵', name: 'sailboat', category: 'Travel' },
  { emoji: '⚓', name: 'anchor', category: 'Travel' },
  { emoji: '⛽', name: 'fuel pump', category: 'Travel' },
  { emoji: '🚦', name: 'traffic light', category: 'Travel' },

  // Objects & Tools
  { emoji: '💻', name: 'laptop', category: 'Objects' },
  { emoji: '📱', name: 'mobile', category: 'Objects' },
  { emoji: '☎️', name: 'telephone', category: 'Objects' },
  { emoji: '⌨️', name: 'keyboard', category: 'Objects' },
  { emoji: '🖥️', name: 'desktop', category: 'Objects' },
  { emoji: '🖨️', name: 'printer', category: 'Objects' },
  { emoji: '📸', name: 'camera', category: 'Objects' },
  { emoji: '🎥', name: 'video camera', category: 'Objects' },
  { emoji: '📺', name: 'tv', category: 'Objects' },
  { emoji: '📻', name: 'radio', category: 'Objects' },
  { emoji: '⏰', name: 'alarm clock', category: 'Objects' },
  { emoji: '💡', name: 'light bulb', category: 'Objects' },
  { emoji: '🔦', name: 'flashlight', category: 'Objects' },
  { emoji: '🕯️', name: 'candle', category: 'Objects' },
  { emoji: '🔨', name: 'hammer', category: 'Objects' },
  { emoji: '🔧', name: 'wrench', category: 'Objects' },
  { emoji: '🔩', name: 'nut and bolt', category: 'Objects' },
  { emoji: '🔫', name: 'water pistol', category: 'Objects' },
  { emoji: '💸', name: 'money', category: 'Objects' },
  { emoji: '💵', name: 'dollar bill', category: 'Objects' },
  { emoji: '💳', name: 'credit card', category: 'Objects' },
  { emoji: '💎', name: 'gem', category: 'Objects' },
  { emoji: '⚖️', name: 'balance scale', category: 'Objects' },
  { emoji: '🔗', name: 'link', category: 'Objects' },
  { emoji: '⛓️', name: 'chains', category: 'Objects' },
  { emoji: '💉', name: 'syringe', category: 'Objects' },
  { emoji: '💊', name: 'pill', category: 'Objects' },
  { emoji: '🚪', name: 'door', category: 'Objects' },
  { emoji: '🛏️', name: 'bed', category: 'Objects' },
  { emoji: '🛋️', name: 'couch', category: 'Objects' },
  { emoji: '🚿', name: 'shower', category: 'Objects' },
  { emoji: '🛁', name: 'bathtub', category: 'Objects' },
  { emoji: '🔑', name: 'key', category: 'Objects' },
  { emoji: '🧹', name: 'broom', category: 'Objects' },

  // Activities & Hobbies
  { emoji: '⚽', name: 'soccer', category: 'Activities' },
  { emoji: '🏀', name: 'basketball', category: 'Activities' },
  { emoji: '🏈', name: 'football', category: 'Activities' },
  { emoji: '⚾', name: 'baseball', category: 'Activities' },
  { emoji: '🎾', name: 'tennis', category: 'Activities' },
  { emoji: '🏐', name: 'volleyball', category: 'Activities' },
  { emoji: '🏉', name: 'rugby', category: 'Activities' },
  { emoji: '🎱', name: 'pool', category: 'Activities' },
  { emoji: '⛳', name: 'golf', category: 'Activities' },
  { emoji: '🪁', name: 'kite', category: 'Activities' },
  { emoji: '🏹', name: 'bow and arrow', category: 'Activities' },
  { emoji: '🎣', name: 'fishing', category: 'Activities' },
  { emoji: '🥊', name: 'boxing', category: 'Activities' },
  { emoji: '🥋', name: 'martial arts', category: 'Activities' },
  { emoji: '⛸️', name: 'ice skate', category: 'Activities' },
  { emoji: '🎿', name: 'ski', category: 'Activities' },
  { emoji: '🏂', name: 'snowboard', category: 'Activities' },
  { emoji: '🏋️', name: 'weightlifter', category: 'Activities' },
  { emoji: '🤺', name: 'fencing', category: 'Activities' },
  { emoji: '🤼', name: 'wrestling', category: 'Activities' },
  { emoji: '🤸', name: 'cartwheel', category: 'Activities' },
  { emoji: '🏆', name: 'trophy', category: 'Activities' },
  { emoji: '🏅', name: 'medal', category: 'Activities' },
  { emoji: '🥇', name: 'first place', category: 'Activities' },
  { emoji: '🎟️', name: 'ticket', category: 'Activities' },
  { emoji: '🎮', name: 'video game', category: 'Activities' },
  { emoji: '🎲', name: 'die', category: 'Activities' },
  { emoji: '♟️', name: 'chess', category: 'Activities' },
  { emoji: '🎹', name: 'piano', category: 'Activities' },
  { emoji: '🎸', name: 'guitar', category: 'Activities' },
  { emoji: '🎺', name: 'trumpet', category: 'Activities' },
  { emoji: '🎻', name: 'violin', category: 'Activities' },
  { emoji: '🥁', name: 'drum', category: 'Activities' },
  { emoji: '🎭', name: 'performing arts', category: 'Activities' },
  { emoji: '🎨', name: 'artist palette', category: 'Activities' },
  { emoji: '🎬', name: 'clapper board', category: 'Activities' },
  { emoji: '🎤', name: 'microphone', category: 'Activities' },
  { emoji: '🎧', name: 'headphone', category: 'Activities' },
];
